# Deployment Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaopeso
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appconversaopeso
  template:
    metadata:
      labels:
        app: appconversaopeso
    spec:
      containers:
      - name: appconversaopeso
        image: elainecro/conversao-peso:v1
        ports:
        - containerPort: 80
---
# Service app web
apiVersion: v1
kind: Service
metadata:
  name: conversaopeso
spec:
  selector:
    app: appconversaopeso
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30000
  type: LoadBalancer